(() => {
  const localBase = "http://127.0.0.1:8766";
  const cloudBase = `${window.location.protocol}//${window.location.hostname}:8765`;
  const storageKey = "c2s.collectorSessionId";
  const $c = (selector) => document.querySelector(selector);
  const interfaceSelect = $c("#collector-interface");
  const startButton = $c("#collector-start-btn");
  const stopButton = $c("#collector-stop-btn");
  const message = $c("#collector-message");
  const overall = $c("#collector-overall-state");
  const guide = $c("#collector-install-guide");
  const livePanel = $c(".collector-live-panel");
  let pollTimer = null;
  let cloudPollTimer = null;
  let cloudEvents = null;
  let sessionId = window.localStorage.getItem(storageKey);
  let completedAnalysisId = null;

  const labels = { idle:"等待开始", starting:"正在启动", capturing:"正在采集", stopping:"正在停止", hashing:"正在校验文件", uploading:"正在上传", completed:"上传完成", upload_failed:"上传失败", capture_failed:"采集失败" };
  const formatBytes = (value) => { const bytes=Number(value)||0; if(bytes<1024)return `${bytes} B`; if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`; return `${(bytes/1048576).toFixed(1)} MB`; };
  const formatDuration = (seconds) => { const value=Math.max(0,Number(seconds)||0); return [Math.floor(value/3600),Math.floor(value%3600/60),value%60].map(item=>String(item).padStart(2,"0")).join(":"); };
  const apiError = async (response) => { try { return (await response.json()).detail || `请求失败（${response.status}）`; } catch { return `请求失败（${response.status}）`; } };
  const setIndicator = (name, ok, text) => { const indicator=$c(`#collector-${name}-indicator`); indicator.className=`environment-indicator ${ok ? "ok" : "error"}`; indicator.textContent=ok?"✓":"!"; $c(`#collector-${name}-status`).textContent=text; };
  const setStage = (stage) => { const order=["environment","config","capture","analysis","result"]; const index=order.indexOf(stage); document.querySelectorAll("[data-collector-stage]").forEach((item,itemIndex)=>item.classList.toggle("active",itemIndex<=index)); };
  const markAnalysisStep = (step) => { const order=["zeek","rita","lstm","rag","ai"]; const index=order.indexOf(step); $c("#collector-analysis-steps").querySelectorAll("li").forEach((item,itemIndex)=>{item.classList.remove("active","done"); if(itemIndex<index)item.classList.add("done"); if(itemIndex===index)item.classList.add("active");}); };

  const applyLocalStatus = (data) => {
    const ready=Boolean(data.ready); overall.classList.toggle("ready",ready); overall.querySelector("span").textContent=ready?"采集环境已就绪":"采集环境需要处理";
    setIndicator("app",true,"本地控制器已连接"); setIndicator("dumpcap",Boolean(data.dumpcap_available),data.dumpcap_available?"已发现 dumpcap.exe":"未发现 dumpcap.exe，请安装 Wireshark");
    setIndicator("npcap",Boolean(data.npcap_available),data.npcap_available?"Npcap 与网卡访问正常":(data.environment_error||"Npcap 或网卡权限不可用")); guide.hidden=ready;
    const interfaces=Array.isArray(data.interfaces)?data.interfaces:[]; if(interfaces.length){const previous=interfaceSelect.value; interfaceSelect.replaceChildren(...interfaces.map(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=item.display_name||item.description||item.name;return option;})); if(interfaces.some(item=>item.id===previous))interfaceSelect.value=previous;}
    interfaceSelect.disabled=!ready; const state=data.capture_status||"idle"; const busy=["starting","capturing","stopping","hashing","uploading"].includes(state); startButton.disabled=!ready||busy; stopButton.disabled=!(["capturing","upload_failed"].includes(state)); livePanel.classList.toggle("running",busy);
    $c("#collector-live-status").textContent=labels[state]||state; $c("#collector-elapsed").textContent=formatDuration(data.elapsed_seconds); $c("#collector-bytes").textContent=formatBytes(data.captured_bytes);
    if(data.cloud_session_id){sessionId=data.cloud_session_id;window.localStorage.setItem(storageKey,sessionId);$c("#collector-session-label").textContent=sessionId.slice(0,8);}
    if(state==="capturing")setStage("capture"); if(["hashing","uploading","completed"].includes(state)){setStage("analysis");startCloudEvents();} if(state.endsWith("failed")){message.textContent=data.last_error||"任务失败，请重试";message.classList.add("error");}
  };

  const checkEnvironment = async (refresh=false) => { try { const response=await fetch(`${localBase}/status${refresh?"?refresh=true":""}`,{cache:"no-store"}); if(!response.ok)throw new Error(await apiError(response)); const data=await response.json();applyLocalStatus(data);message.textContent=data.ready?"采集环境已就绪。":"请根据左侧提示完成安装或权限设置。";message.classList.toggle("error",!data.ready); } catch(error){overall.classList.remove("ready");overall.querySelector("span").textContent="未检测到本地控制器";setIndicator("app",false,"请下载并运行 C2Sherlock 本地采集控制器");setIndicator("dumpcap",false,"等待控制器检查");setIndicator("npcap",false,"等待控制器检查");guide.hidden=false;interfaceSelect.disabled=true;startButton.disabled=true;message.textContent=error instanceof Error?error.message:"无法连接本地控制器";message.classList.add("error");} };
  const pollLocal = () => { window.clearInterval(pollTimer);pollTimer=window.setInterval(checkEnvironment,1000); };
  const createCloudSession = async () => { const response=await fetch(`${cloudBase}/collector/sessions`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({model_id:$c("#collector-model").value})}); if(response.status===401)throw new Error("在线采集需要先登录账号"); if(!response.ok)throw new Error(await apiError(response)); return response.json(); };
  const startCapture = async () => { if(!window.confirm("即将采集本机网络流量，并在停止后上传至 C2Sherlock 云端分析。\n\n请确认已获得设备与网络的授权。"))return; startButton.disabled=true; message.classList.remove("error");message.textContent="正在创建云端会话…"; try { const session=await createCloudSession();sessionId=session.session_id;window.localStorage.setItem(storageKey,sessionId);$c("#collector-session-label").textContent=sessionId.slice(0,8);const response=await fetch(`${localBase}/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({interface_id:interfaceSelect.value,capture_filter:$c("#collector-filter").value||"tcp or udp",max_duration_seconds:Number($c("#collector-duration").value),max_file_size_mb:Number($c("#collector-max-size").value),cloud_session_id:session.session_id,upload_token:session.upload_token})});if(!response.ok)throw new Error(await apiError(response));applyLocalStatus(await response.json());message.textContent="正在采集本机网络流量。达到时长或大小限制后会自动停止并上传。";pollLocal();}catch(error){message.textContent=error instanceof Error?error.message:"启动采集失败";message.classList.add("error");startButton.disabled=false;} };
  const stopCapture = async () => { stopButton.disabled=true;message.textContent="正在正常停止 dumpcap 并关闭 PCAPNG 文件…";try{const response=await fetch(`${localBase}/stop`,{method:"POST"});if(!response.ok)throw new Error(await apiError(response));applyLocalStatus(await response.json());setStage("analysis");startCloudEvents();}catch(error){message.textContent=error instanceof Error?error.message:"停止采集失败";message.classList.add("error");stopButton.disabled=false;} };
  const loadCompletedResult = async (analysisId) => { const response=await fetch(`${cloudBase}/analyses/${analysisId}/dashboard`,{credentials:"include"});if(!response.ok)throw new Error(await apiError(response));const payload=await response.json();completedAnalysisId=analysisId;$c("#collector-open-data-btn").disabled=false;window.C2SherlockCollectorResult=payload;setStage("result");message.textContent="云端分析完成，可查看完整报告与可视化数据。";window.localStorage.removeItem(storageKey);sessionId=null;window.clearInterval(cloudPollTimer); };
  const pollCloud = async () => { if(!sessionId)return;try{const response=await fetch(`${cloudBase}/collector/sessions/${sessionId}`,{credentials:"include",cache:"no-store"});if(!response.ok){if(response.status===404)window.localStorage.removeItem(storageKey);return;}const data=await response.json();if(data.current_step)markAnalysisStep(data.current_step);if(data.status==="completed"&&data.analysis_record_id){window.clearInterval(cloudPollTimer);await loadCompletedResult(data.analysis_record_id);}else if(data.status==="failed"){window.clearInterval(cloudPollTimer);message.textContent=data.error_message||"云端分析失败";message.classList.add("error");}else if(["queued","analyzing"].includes(data.status)){setStage("analysis");$c("#collector-live-status").textContent=data.current_step?`云端分析：${data.current_step.toUpperCase()}`:"等待云端分析";}}catch(error){console.warn("恢复采集会话失败",error);} };
  const startCloudPolling = () => { if(!sessionId)return;window.clearInterval(cloudPollTimer);void pollCloud();cloudPollTimer=window.setInterval(pollCloud,1500); };
  const startCloudEvents = () => { if(!sessionId||cloudEvents)return;void pollCloud();cloudEvents=new EventSource(`${cloudBase}/collector/sessions/${sessionId}/events`,{withCredentials:true});cloudEvents.addEventListener("step",event=>{try{const payload=JSON.parse(event.data);markAnalysisStep(payload.step);$c("#collector-live-status").textContent=`云端分析：${payload.step.toUpperCase()}`;}catch{}});cloudEvents.addEventListener("completed",event=>{try{const payload=JSON.parse(event.data);cloudEvents.close();cloudEvents=null;void loadCompletedResult(payload.analysis_record_id);}catch{}});cloudEvents.addEventListener("failed",event=>{let text="云端分析失败";try{text=JSON.parse(event.data).message||text;}catch{}message.textContent=text;message.classList.add("error");cloudEvents.close();cloudEvents=null;});cloudEvents.onerror=()=>{cloudEvents?.close();cloudEvents=null;startCloudPolling();}; };
  $c("#collector-recheck-btn")?.addEventListener("click",()=>checkEnvironment(true));startButton?.addEventListener("click",startCapture);stopButton?.addEventListener("click",stopCapture);
  $c("#collector-open-data-btn")?.addEventListener("click",()=>{const payload=window.C2SherlockCollectorResult;if(!payload)return;document.querySelector('[data-tab="capability"]')?.click();window.C2SherlockVisualization?.render(payload.dashboard,payload.analysis);});
  const collectorTab=$c('[data-tab="collector"]');collectorTab?.addEventListener("click",()=>{void checkEnvironment();if(sessionId)startCloudEvents();});
  if(window.location.hash.replace(/^#/,"").split("?",1)[0]==="collector"){void checkEnvironment();if(sessionId)startCloudEvents();}
})();
