(() => {
  const localBase = "http://127.0.0.1:8766";
  const cloudBase = `${window.location.protocol}//${window.location.hostname}:8765`;
  const storageKey = "c2s.collectorSessionId";
  const $c = (selector) => document.querySelector(selector);
  const interfaceSelect = $c("#collector-interface");
  const startButton = $c("#collector-start-btn");
  const stopButton = $c("#collector-stop-btn");
  const message = $c("#collector-message");
  const overall = $c("#collector-overall-state");
  const guide = $c("#collector-install-guide");
  const livePanel = $c(".collector-live-panel");
  let pollTimer = null;
  let cloudPollTimer = null;
  let cloudEvents = null;
  let sessionId = window.localStorage.getItem(storageKey);
  let completedAnalysisId = null;
  let latestCapturedBytes = 0;
  let cloudProcessing = Boolean(sessionId);

  const labels = { idle:"等待开始", creating_session:"正在创建云端会话", starting:"正在启动监测", capturing:"正在采集", capturing_uploading:"正在采集并同步", sync_delayed:"采集正常，同步稍有延迟", sync_retrying:"网络波动，正在重新同步", stopping:"正在停止监测", flushing:"正在关闭采集数据", hashing:"正在校验采集数据", uploading:"正在同步采集数据", uploading_remaining:"正在同步剩余数据", finalizing:"云端正在整理数据", verifying_chunks:"云端正在校验数据", merging:"云端正在整理数据", completed:"检测完成", upload_failed:"同步失败", capture_failed:"采集失败", merge_failed:"数据整理失败", analysis_failed:"云端检测失败" };
  const formatBytes = (value) => { const bytes=Number(value)||0; if(bytes<1024)return `${bytes} B`; if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`; return `${(bytes/1048576).toFixed(1)} MB`; };
  const formatDuration = (seconds) => { const value=Math.max(0,Number(seconds)||0); return [Math.floor(value/3600),Math.floor(value%3600/60),value%60].map(item=>String(item).padStart(2,"0")).join(":"); };
  const apiError = async (response) => { try { return (await response.json()).detail || `请求失败（${response.status}）`; } catch { return `请求失败（${response.status}）`; } };
  const setIndicator = (name, ok, text) => { const indicator=$c(`#collector-${name}-indicator`); indicator.className=`environment-indicator ${ok ? "ok" : "error"}`; indicator.textContent=ok?"✓":"!"; $c(`#collector-${name}-status`).textContent=text; };
  const setStage = (stage) => { const order=["environment","config","capture","analysis","result"]; const index=order.indexOf(stage); document.querySelectorAll("[data-collector-stage]").forEach((item,itemIndex)=>item.classList.toggle("active",itemIndex<=index)); };
  const markAnalysisStep = (step) => { const order=["zeek","rita","lstm","rag","ai"]; const index=order.indexOf(step); $c("#collector-analysis-steps").querySelectorAll("li").forEach((item,itemIndex)=>{item.classList.remove("active","done"); if(itemIndex<index)item.classList.add("done"); if(itemIndex===index)item.classList.add("active");}); };

  const setText = (selector,value) => { const element=$c(selector); if(element)element.textContent=value; };
  const formatClock = (value) => { if(!value)return "--";const date=new Date(value);return Number.isNaN(date.getTime())?"--":date.toLocaleTimeString("zh-CN",{hour12:false}); };
  const stepLabel = (step) => ({zeek:"日志解析",rita:"规则检测",lstm:"LSTM 时序检测",rag:"RAG 溯源归因",ai:"大模型研判"}[step]||"完整检测");
  const updateSyncDisplay = (data={}) => {
    const captured=Math.max(0,Number(data.captured_bytes??latestCapturedBytes)||0);const hasUploaded=data.uploaded_bytes!==undefined&&data.uploaded_bytes!==null;let uploaded=hasUploaded?Math.max(0,Number(data.uploaded_bytes)||0):null;if(uploaded===null&&data.capture_status==="completed")uploaded=captured;if(uploaded!==null)uploaded=Math.min(uploaded,captured||uploaded);
    setText("#collector-uploaded-bytes",uploaded===null?"等待同步数据":formatBytes(uploaded));const percent=captured>0&&uploaded!==null?Math.min(100,uploaded/captured*100):0;const bar=$c("#collector-sync-progress");if(bar){bar.style.width=`${percent}%`;bar.parentElement?.setAttribute("aria-valuenow",String(Math.round(percent)));}
    const pending=uploaded===null?null:Math.max(0,captured-uploaded);const state=data.capture_status||data.status||"idle";
    if(state==="idle"){setText("#collector-sync-status","开始监测后，采集数据将持续同步至云端。");setText("#collector-sync-detail","等待开始");}
    else if(["sync_delayed","sync_retrying","upload_failed"].includes(state)){setText("#collector-sync-status",state==="upload_failed"?"同步暂时中断，采集数据已安全保留在本机。":"网络出现波动，系统正在自动同步。");setText("#collector-sync-detail",pending===null?"正在自动重试":`待同步 ${formatBytes(pending)}`);}
    else if(state==="completed"||(uploaded!==null&&captured>0&&pending===0)){setText("#collector-sync-status","采集数据已同步至云端。");setText("#collector-sync-detail",`已同步 ${formatBytes(uploaded||0)}`);}
    else{setText("#collector-sync-status","采集数据正在持续同步至云端。");setText("#collector-sync-detail",pending===null?"等待云端确认":`已同步 ${formatBytes(uploaded)}，待同步 ${formatBytes(pending)}`);}
    setText("#collector-last-sync",`最近同步：${formatClock(data.last_sync_at||data.updated_at)}`);
  };
  const renderAlerts = (alerts) => { const list=$c("#collector-alert-list");if(!list)return;const items=Array.isArray(alerts)?alerts.slice(0,3):[];list.replaceChildren(...items.map(alert=>{const item=document.createElement("article");item.className="collector-alert-item";const content=document.createElement("div");const title=document.createElement("strong");title.textContent=`${alert.source||alert.source_ip||"未知来源"} → ${alert.destination||alert.destination_ip||"未知目标"}`;const summary=document.createElement("p");summary.textContent=`${alert.summary||"发现可疑连接行为"} · ${Array.isArray(alert.engines)?alert.engines.join(" + "):(alert.engine||"检测引擎")}`;content.append(title,summary);const severity=document.createElement("span");severity.className="collector-alert-severity";severity.textContent=alert.severity==="high"?"高风险":alert.severity==="medium"?"中风险":"可疑";item.append(content,severity);return item;}));list.hidden=!items.length; };
  const updateDetectionDisplay = (data={}) => {
    const panel=$c("#collector-detection-panel");const suspiciousRaw=data.suspicious_count;const suspicious=suspiciousRaw===undefined||suspiciousRaw===null?null:Number(suspiciousRaw)||0;const analyzedRaw=data.analyzed_bytes;const analyzed=analyzedRaw===undefined||analyzedRaw===null?null:Number(analyzedRaw)||0;const connectionsRaw=data.connection_count??data.checked_connections;const connections=connectionsRaw===undefined||connectionsRaw===null?null:Number(connectionsRaw)||0;
    setText("#collector-analyzed-bytes",analyzed===null?"等待检测":formatBytes(analyzed));setText("#collector-suspicious-count",suspicious===null?"--":String(suspicious));setText("#collector-connection-count",connections===null?"--":connections.toLocaleString("zh-CN"));setText("#collector-last-analyzed",formatClock(data.last_analyzed_at));panel?.classList.remove("neutral","clean","alert","analyzing");
    if(suspicious!==null&&suspicious>0){panel?.classList.add("alert");setText("#collector-detection-indicator","!");setText("#collector-detection-badge",`发现 ${suspicious} 条`);setText("#collector-detection-summary",`已发现 ${suspicious} 条可疑连接，正在持续收集和复核证据。`);setText("#collector-analysis-note","停止监测并完成同步后，系统将汇总检测证据并生成智能研判报告。");renderAlerts(data.recent_alerts||data.alerts);}
    else if(suspicious===0&&analyzed!==null){panel?.classList.add("clean");setText("#collector-detection-indicator","✓");setText("#collector-detection-badge","暂未发现威胁");setText("#collector-detection-summary","当前未发现可疑连接，系统将继续分析后续网络活动。");renderAlerts([]);}
    else if(["queued","analyzing"].includes(data.status)||data.current_step){panel?.classList.add("analyzing");setText("#collector-detection-indicator","…");setText("#collector-detection-badge","正在检测");setText("#collector-detection-summary",data.current_step?`云端正在执行${stepLabel(data.current_step)}。`:"正在分析最新同步数据。");}
    else{panel?.classList.add("neutral");setText("#collector-detection-indicator","○");setText("#collector-detection-badge","等待数据");setText("#collector-detection-summary","开始监测后，系统将分析已同步的网络流量。");renderAlerts([]);}
  };

  const applyLocalStatus = (data) => {
    const ready=Boolean(data.ready); overall.classList.toggle("ready",ready); overall.querySelector("span").textContent=ready?"采集环境已就绪":"采集环境需要处理";
    setIndicator("app",true,"本地控制器已连接"); setIndicator("dumpcap",Boolean(data.dumpcap_available),data.dumpcap_available?"已发现 dumpcap.exe":"未发现 dumpcap.exe，请安装 Wireshark");
    setIndicator("npcap",Boolean(data.npcap_available),data.npcap_available?"Npcap 与网卡访问正常":(data.environment_error||"Npcap 或网卡权限不可用")); guide.hidden=ready;
    const interfaces=Array.isArray(data.interfaces)?data.interfaces:[]; if(interfaces.length){const previous=interfaceSelect.value; interfaceSelect.replaceChildren(...interfaces.map(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=item.display_name||item.description||item.name;return option;})); if(interfaces.some(item=>item.id===previous))interfaceSelect.value=previous;}
    interfaceSelect.disabled=!ready; const localState=data.capture_status||"idle";const state=localState==="completed"&&cloudProcessing?"finalizing":localState; const busy=cloudProcessing||["creating_session","starting","capturing","capturing_uploading","sync_delayed","sync_retrying","stopping","flushing","hashing","uploading","uploading_remaining","finalizing","verifying_chunks","merging"].includes(state); startButton.disabled=!ready||busy; stopButton.disabled=!["capturing","capturing_uploading","sync_delayed","sync_retrying","upload_failed"].includes(localState); livePanel.classList.toggle("running",busy);
    latestCapturedBytes=Math.max(0,Number(data.captured_bytes)||0);$c("#collector-live-status").textContent=labels[state]||state; $c("#collector-elapsed").textContent=formatDuration(data.elapsed_seconds); $c("#collector-bytes").textContent=formatBytes(latestCapturedBytes);
    if(data.cloud_session_id){sessionId=data.cloud_session_id;window.localStorage.setItem(storageKey,sessionId);$c("#collector-session-label").textContent=`会话 ${sessionId.slice(0,8)}`;}
    updateSyncDisplay(data);if(data.analyzed_bytes!==undefined||data.suspicious_count!==undefined||data.detection_status)updateDetectionDisplay(data);
    if(["capturing","capturing_uploading","sync_delayed","sync_retrying"].includes(state))setStage("capture"); if(["hashing","uploading","uploading_remaining","finalizing","verifying_chunks","merging","completed"].includes(state)){setStage("analysis");startCloudEvents();} if(state.endsWith("failed")){message.textContent=data.last_error||"任务失败，请重试";message.classList.add("error");}
  };

  const checkEnvironment = async (refresh=false) => { try { const response=await fetch(`${localBase}/status${refresh?"?refresh=true":""}`,{cache:"no-store"}); if(!response.ok)throw new Error(await apiError(response)); const data=await response.json();applyLocalStatus(data);const state=data.capture_status||"idle";if(state==="idle"){message.textContent=data.ready?"采集环境已就绪。":"请根据左侧提示完成安装或权限设置。";message.classList.toggle("error",!data.ready);}else if(!state.endsWith("failed")){message.classList.remove("error");} } catch(error){overall.classList.remove("ready");overall.querySelector("span").textContent="未检测到本地控制器";setIndicator("app",false,"请下载并运行 C2Sherlock 本地采集控制器");setIndicator("dumpcap",false,"等待控制器检查");setIndicator("npcap",false,"等待控制器检查");guide.hidden=false;interfaceSelect.disabled=true;startButton.disabled=true;message.textContent=error instanceof Error?error.message:"无法连接本地控制器";message.classList.add("error");} };
  const pollLocal = () => { window.clearInterval(pollTimer);pollTimer=window.setInterval(checkEnvironment,1000); };
  const createCloudSession = async () => { const response=await fetch(`${cloudBase}/collector/sessions`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({model_id:$c("#collector-model").value})}); if(response.status===401)throw new Error("在线监测需要先登录账号"); if(!response.ok)throw new Error(await apiError(response)); return response.json(); };
  const startCapture = async () => { if(!window.confirm("即将采集本机网络流量。\n\n采集数据将持续同步至 C2Sherlock 云端进行检测，并生成多引擎检测结果与智能研判报告。\n\n请确认已获得设备与网络的授权。"))return; startButton.disabled=true; message.classList.remove("error");message.textContent="正在创建云端检测会话…";setText("#collector-live-status",labels.creating_session); try { const session=await createCloudSession();sessionId=session.session_id;cloudProcessing=true;window.localStorage.setItem(storageKey,sessionId);$c("#collector-session-label").textContent=`会话 ${sessionId.slice(0,8)}`;startCloudEvents();const response=await fetch(`${localBase}/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({interface_id:interfaceSelect.value,capture_filter:$c("#collector-filter").value||"tcp or udp",max_duration_seconds:Number($c("#collector-duration").value),max_file_size_mb:100,cloud_session_id:session.session_id,upload_token:session.upload_token})});if(!response.ok)throw new Error(await apiError(response));applyLocalStatus(await response.json());message.textContent="正在采集本机网络流量并同步至云端。";pollLocal();}catch(error){cloudEvents?.close();cloudEvents=null;cloudProcessing=false;window.localStorage.removeItem(storageKey);sessionId=null;message.textContent=error instanceof Error?error.message:"启动在线监测失败";message.classList.add("error");startButton.disabled=false;} };
  const stopCapture = async () => { stopButton.disabled=true;message.textContent="正在停止监测并同步剩余数据…";try{const response=await fetch(`${localBase}/stop`,{method:"POST"});if(!response.ok)throw new Error(await apiError(response));applyLocalStatus(await response.json());setStage("analysis");startCloudEvents();}catch(error){message.textContent=error instanceof Error?error.message:"停止在线监测失败";message.classList.add("error");stopButton.disabled=false;} };
  const loadCompletedResult = async (analysisId) => { const response=await fetch(`${cloudBase}/analyses/${analysisId}/dashboard`,{credentials:"include"});if(!response.ok)throw new Error(await apiError(response));const payload=await response.json();cloudProcessing=false;completedAnalysisId=analysisId;const threats=Array.isArray(payload.dashboard?.threats)?payload.dashboard.threats:[];updateDetectionDisplay({analyzed_bytes:payload.analysis?.file_size,suspicious_count:threats.length,connection_count:payload.dashboard?.connection_count,last_analyzed_at:new Date().toISOString(),recent_alerts:threats});const openButton=$c("#collector-open-data-btn");openButton.disabled=false;openButton.classList.add("ready");window.C2SherlockCollectorResult=payload;setStage("result");message.textContent=threats.length?"检测完成，已发现可疑连接并生成研判结果。":"检测完成，本次暂未发现可疑连接。";setText("#collector-live-status","检测完成");window.localStorage.removeItem(storageKey);sessionId=null;window.clearInterval(cloudPollTimer);window.clearInterval(pollTimer); };
  const pollCloud = async () => { if(!sessionId)return;try{const response=await fetch(`${cloudBase}/collector/sessions/${sessionId}`,{credentials:"include",cache:"no-store"});if(!response.ok){if(response.status===404){cloudProcessing=false;window.localStorage.removeItem(storageKey);sessionId=null;}return;}const data=await response.json();if(data.current_step)markAnalysisStep(data.current_step);if(data.received_bytes!==undefined)updateSyncDisplay({status:data.status,captured_bytes:Math.max(latestCapturedBytes,Number(data.file_size??data.received_bytes)||0),uploaded_bytes:data.received_bytes,updated_at:data.updated_at});updateDetectionDisplay(data);if(data.status==="completed"&&data.analysis_record_id){window.clearInterval(cloudPollTimer);await loadCompletedResult(data.analysis_record_id);}else if(data.status==="failed"){cloudProcessing=false;window.clearInterval(cloudPollTimer);message.textContent=data.error_message||"云端检测失败";message.classList.add("error");setText("#collector-live-status","云端检测失败");}else if(["finalizing","merging","queued","analyzing"].includes(data.status)){setStage("analysis");$c("#collector-live-status").textContent=data.current_step?`云端检测：${stepLabel(data.current_step)}`:(labels[data.status]||"等待云端检测");}}catch(error){console.warn("恢复在线监测会话失败",error);} };
  const startCloudPolling = () => { if(!sessionId)return;window.clearInterval(cloudPollTimer);void pollCloud();cloudPollTimer=window.setInterval(pollCloud,1500); };
  const startCloudEvents = () => { if(!sessionId||cloudEvents)return;void pollCloud();cloudEvents=new EventSource(`${cloudBase}/collector/sessions/${sessionId}/events`,{withCredentials:true});cloudEvents.addEventListener("step",event=>{try{const payload=JSON.parse(event.data);markAnalysisStep(payload.step);updateDetectionDisplay({status:"analyzing",current_step:payload.step});$c("#collector-live-status").textContent=`云端检测：${stepLabel(payload.step)}`;}catch{}});cloudEvents.addEventListener("sync_progress",event=>{try{const payload=JSON.parse(event.data);updateSyncDisplay({status:"receiving",uploaded_bytes:payload.uploaded_bytes,updated_at:payload.updated_at});}catch{}});cloudEvents.addEventListener("detection_update",event=>{try{updateDetectionDisplay(JSON.parse(event.data));}catch{}});cloudEvents.addEventListener("suspicious_connection",event=>{try{updateDetectionDisplay(JSON.parse(event.data));}catch{}});["finalizing","merging"].forEach(type=>cloudEvents.addEventListener(type,()=>{setStage("analysis");setText("#collector-live-status",labels[type]);}));cloudEvents.addEventListener("completed",event=>{try{const payload=JSON.parse(event.data);cloudEvents.close();cloudEvents=null;void loadCompletedResult(payload.analysis_record_id);}catch{}});cloudEvents.addEventListener("failed",event=>{let text="云端检测失败";try{text=JSON.parse(event.data).message||text;}catch{}cloudProcessing=false;message.textContent=text;message.classList.add("error");cloudEvents.close();cloudEvents=null;});cloudEvents.onerror=()=>{cloudEvents?.close();cloudEvents=null;startCloudPolling();}; };
  $c("#collector-recheck-btn")?.addEventListener("click",()=>checkEnvironment(true));startButton?.addEventListener("click",startCapture);stopButton?.addEventListener("click",stopCapture);
  $c("#collector-open-data-btn")?.addEventListener("click",()=>{const payload=window.C2SherlockCollectorResult;if(!payload)return;document.querySelector('[data-tab="capability"]')?.click();window.C2SherlockVisualization?.render(payload.dashboard,payload.analysis);});
  const collectorTab=$c('[data-tab="collector"]');collectorTab?.addEventListener("click",()=>{void checkEnvironment();if(sessionId)startCloudEvents();});
  if(window.location.hash.replace(/^#/,"").split("?",1)[0]==="collector"){void checkEnvironment();if(sessionId)startCloudEvents();}
})();
